### ISSUE TITLE
Typo in Title

### ISSUE THREAD

**Issue by AALUND13** [Fauzan-A25/Bot_Musik_Discord_V1#1]
There is typo in the repo title.
![image](https://github.com/user-attachments/assets/d60a89ec-dd94-40a8-a560-7f127be7491a)

**Comment by AALUND13** [comment]
Also, I highly recommend reset those API key if you haven't already after the `Update config.json` update.
![image](https://github.com/user-attachments/assets/984524f4-62ea-436b-a618-df11e41704a1)

**Comment by AALUND13** [comment]
I check the `commands` folder and it also have the same typo for folder name `musik`, And I starting think it not a typo XD.

**Comment by Fauzan-A25** [comment]
> I check the `commands` folder and it also have the same typo for folder name `musik`, And I starting think it not a typo XD.

haha, sory bro that its name from my country XD
